kind: pipeline
type: kubernetes
name: run-on-cron

steps:
  - name: generate-timestamp
    image: alpine:latest
    commands:
      - echo -n "$(date +%Y%m%d-%H%M%S)" > .tags
      - echo -n "latest" >> .tags

  - name: build-and-push-image
    image: plugins/docker
    settings:
      username: mellena1
      password:
        from_secret: docker_password
      repo: mellena1/dev-environment
      tags_file: .tags

trigger:
  cron:
    - daily
  event:
    - cron

---
kind: pipeline
type: kubernetes
name: run-on-main

steps:
  - name: generate-timestamp
    image: alpine:latest
    commands:
      - echo -n "$(date +%Y%m%d-%H%M%S)" > .tags
      - echo -n "latest" >> .tags

  - name: build-and-push-image
    image: plugins/docker
    settings:
      username: mellena1
      password:
        from_secret: docker_password
      repo: mellena1/dev-environment
      tags_file: .tags

trigger:
  branch:
    - main
  event:
    - push
